import subprocess
import time


print("Opening")
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T1" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial4" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T1" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial5" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T1" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial6" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T1" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial7" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T1" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial8" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T1" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial9" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T1" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial10" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T2" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial4" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T2" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial5" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T2" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial6" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T2" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial7" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T2" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial8" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T2" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial9" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T2" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial10" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T3" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial4" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T3" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial5" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T3" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial6" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T3" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial7" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T3" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial8" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T3" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial9" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T3" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial10" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T4" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial4" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T4" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial5" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T4" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial6" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T4" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial7" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T4" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial8" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T4" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial9" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T4" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial10" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T5" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial4" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T5" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial5" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T5" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial6" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T5" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial7" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T5" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial8" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T5" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial9" ',shell=True)
time.sleep(0.2)
subprocess.call('python swarm_movement.py --N-robots 100 --exp-name "WEBOTS-SOL3-T5" --visdom-name "repeated_experiment_N=100" --trial "POS1-Trial10" ',shell=True)
time.sleep(0.2)